import type { CanvasNodeType } from '../../../shared/types/investigation'
import type { EvidenceFieldDefinition, KnowledgeBase } from '../../../shared/types/knowledge'
import { localize, type Locale, type TranslationKey } from '../../../shared/i18n'

export type LibraryCategory =
  | 'tactics'
  | 'techniques'
  | 'useCases'
  | 'alerts'
  | 'evidence'
  | 'analystNotes'
  | string

export interface LibraryItem {
  definitionId: string
  nodeType: CanvasNodeType
  label: string
  category: LibraryCategory
  brief?: string
  fieldDefinitions: EvidenceFieldDefinition[]
  isUseCase?: boolean
}

export const CATEGORY_TRANSLATION_KEYS: Record<string, TranslationKey> = {
  tactics: 'category.tactics',
  techniques: 'category.techniques',
  useCases: 'category.useCases',
  alerts: 'category.alerts',
  authentication: 'category.authentication',
  identity: 'category.identity',
  infrastructure: 'category.infrastructure',
  evidence: 'category.evidence',
  analystNotes: 'category.analystNotes',
}

export function buildGenericItems(locale: Locale): LibraryItem[] {
  return [
    {
      definitionId: 'generic.alert',
      nodeType: 'alert',
      label: localize({ en: 'Alert', pt: 'Alerta', de: 'Alarm' }, locale),
      category: 'alerts',
      brief: localize(
        {
          en: 'An alert generated by a security tool.',
          pt: 'Um alerta gerado por uma ferramenta de segurança.',
          de: 'Ein von einem Sicherheitstool generierter Alarm.',
        },
        locale,
      ),
      fieldDefinitions: [
        {
          id: 'source_tool',
          label: { en: 'Source tool', pt: 'Ferramenta de origem', de: 'Quell-Tool' },
          type: 'string',
          required: false,
        },
        {
          id: 'severity',
          label: { en: 'Severity', pt: 'Severidade', de: 'Schweregrad' },
          type: 'string',
          required: false,
        },
      ],
    },
    {
      definitionId: 'generic.evidence',
      nodeType: 'evidence',
      label: localize({ en: 'Generic evidence', pt: 'Evidência genérica', de: 'Allgemeines Beweismittel' }, locale),
      category: 'evidence',
      brief: localize(
        {
          en: 'An observed piece of evidence that does not yet have a specific type in the knowledge base.',
          pt: 'Uma evidência observada que ainda não possui um tipo específico na base de conhecimento.',
          de: 'Ein beobachtetes Beweismittel, das noch keinen spezifischen Typ in der Wissensdatenbank hat.',
        },
        locale,
      ),
      fieldDefinitions: [
        {
          id: 'description',
          label: { en: 'Description', pt: 'Descrição', de: 'Beschreibung' },
          type: 'string',
          required: false,
        },
      ],
    },
    {
      definitionId: 'generic.analyst_note',
      nodeType: 'analyst_note',
      label: localize({ en: 'Analyst note', pt: 'Observação do analista', de: 'Analystennotiz' }, locale),
      category: 'analystNotes',
      brief: localize(
        {
          en: 'A free-form note written by the analyst about the investigation.',
          pt: 'Uma anotação livre do analista sobre a investigação.',
          de: 'Eine freie Notiz des Analysten zur Untersuchung.',
        },
        locale,
      ),
      fieldDefinitions: [
        {
          id: 'text',
          label: { en: 'Text', pt: 'Texto', de: 'Text' },
          type: 'string',
          required: false,
        },
      ],
    },
  ]
}

export function buildLibraryItems(knowledgeBase: KnowledgeBase, locale: Locale): LibraryItem[] {
  const tacticItems: LibraryItem[] = knowledgeBase.tactics.map((tactic) => ({
    definitionId: tactic.id,
    nodeType: 'mitre_tactic',
    label: `${tactic.id} - ${tactic.name}`,
    category: 'tactics',
    fieldDefinitions: [],
  }))

  const techniqueItems: LibraryItem[] = knowledgeBase.techniques.map((technique) => ({
    definitionId: technique.id,
    nodeType: technique.type,
    label: `${technique.id} - ${technique.name}`,
    category: 'techniques',
    brief: localize(technique.brief, locale),
    fieldDefinitions: [],
  }))

  const evidenceItems: LibraryItem[] = knowledgeBase.evidenceTypes.map((evidenceType) => ({
    definitionId: evidenceType.id,
    nodeType: evidenceType.node_type,
    label: localize(evidenceType.name, locale),
    category: evidenceType.category,
    brief: localize(evidenceType.brief, locale),
    fieldDefinitions: evidenceType.fields,
  }))

  const useCaseItems: LibraryItem[] = knowledgeBase.useCases.map((useCase) => ({
    definitionId: useCase.id,
    nodeType: 'detection_use_case',
    label: localize(useCase.name, locale),
    category: 'useCases',
    brief: localize(useCase.description, locale),
    fieldDefinitions: [],
    isUseCase: true,
  }))

  return [
    ...tacticItems,
    ...techniqueItems,
    ...evidenceItems,
    ...useCaseItems,
    ...buildGenericItems(locale),
  ]
}
